services:
  db:
    container_name: postgress_db
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    restart: always

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: django
    command: >
      sh -c "python manage.py makemigrations &&
             python manage.py migrate && 
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./core:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    restart: always
  
  redis:
    container_name: redis
    image: redis
    restart: always
    ports:
    - "6380:6379"
    command: redis-server --save 60 1 --loglevel warning

  worker:
    build: .
    command: celery -A core worker --loglevel=info
    volumes:
      - ./core:/app
    depends_on:
      - redis
      - backend

volumes:
  postgres_data: