# Generated by Django 4.2 on 2024-03-24 11:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bookstore", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("author", models.CharField(blank=True, max_length=255, null=True)),
                ("publisher", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("GENERAL", "general"),
                            ("EDUCATIONAL", "educational"),
                            ("HISTORICAL", "historical"),
                            ("CHILDISH", "childish"),
                        ],
                        default="GENERAL",
                        max_length=255,
                    ),
                ),
                ("picture", models.ImageField(blank=True, null=True, upload_to="")),
                ("file", models.BinaryField()),
                ("cost", models.IntegerField(default=0)),
                (
                    "language",
                    models.CharField(
                        choices=[("ENGLISH", "English"), ("PERSIAN", "Persian")],
                        default="ENGLISH",
                        max_length=255,
                    ),
                ),
                ("year", models.IntegerField(blank=True, null=True)),
                ("pages_num", models.IntegerField(blank=True, default=0, null=True)),
                ("is_special", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at", "-updated_at"],
            },
        ),
    ]
