# Generated by Django 4.2 on 2024-03-24 15:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bookstore", "0003_buybook"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="file",
            field=models.CharField(max_length=5111),
        ),
    ]
